name: Car Counting in Video

on:
  workflow_dispatch:
    inputs:
      video_name:
        description: 'The name of the video file in the /videos directory (e.g., my_video.mp4)'
        required: true
        default: 'my_video.mp4'

jobs:
  count-cars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Count cars in video
      run: |
        VIDEO_PATH="./videos/${{ github.event.inputs.video_name }}"
        python count_cars.py $VIDEO_PATH

    - name: Print car count result
      run: echo "Car count completed"
