name: Count Cars

on:
  push:
    paths:
      - '**.py'
      - 'video.mp4'
  workflow_dispatch:

jobs:
  count-cars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python requests

      - name: Show repo files (debug)
        run: ls -lh

      - name: Run car counter
        run: |
          VIDEO_PATH="video.mp4"
          python count_cars.py $VIDEO_PATH
